# -*- coding: utf-8 -*-
"""YorGe_CS_Qwen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYEBPzKzjppIKrDeBCHt1f3RDAzMBXEl
"""

import subprocess
subprocess.run(['pip', 'install', 'transformers', 'peft', 'sentencepiece', 'sacrebleu', 'nltk', 'tqdm', '-q'])
subprocess.run(['pip', 'install', 'torchao>=0.16.0', '--upgrade', '-q'])

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset as TorchDataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer
)
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
from sacrebleu.metrics import BLEU, CHRF
from nltk.translate.meteor_score import meteor_score
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

print("All imports successful!")

from huggingface_hub import login

login(token="YOUR TOKEN")
print("Logged in!")

df = pd.read_csv("/content/drive/MyDrive/yorge_cs.csv")

print(f"Total rows : {len(df)}")
print(df['domain'].value_counts())
df.head(3)

from google.colab import drive
drive.mount('/content/drive')

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['domain']
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42,
    stratify=temp_df['domain']
)

print(f"Train : {len(train_df)} sentences")
print(f"Val   : {len(val_df)} sentences")
print(f"Test  : {len(test_df)} sentences")

test_sources    = test_df['yorge_cs'].tolist()
test_references = test_df['english_translation'].tolist()

model_name = "Qwen/Qwen2.5-3B-Instruct"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    padding_side='left'
)

tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id

print("Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Qwen2.5-3B-Instruct loaded successfully!")

bleu_metric = BLEU(effective_order=True)
chrf_metric = CHRF()

def evaluate(preds, refs, label):
    b = bleu_metric.corpus_score(preds, [refs])
    c = chrf_metric.corpus_score(preds, [refs])
    m = np.mean([
        meteor_score([ref.split()], pred.split())
        for ref, pred in zip(refs, preds)
    ])
    print(f"{label:<35} {b.score:<10.2f} {c.score:<10.2f} {m:.4f}")
    return b.score, c.score, m

def build_zeroshot_prompt(sentence):
    return [
        {
            "role": "system",
            "content": (
                "You are a multilingual translator. "
                "The following sentence is written in Yoruba-German code-switched form, "
                "where Yoruba is the matrix language and German is the embedded language. "
                "Translate it to English. Output only the English translation, "
                "nothing else no explanation, no notes."
            )
        },
        {
            "role": "user",
            "content": sentence
        }
    ]

def translate_qwen(texts, prompt_fn, batch_size=4):
    results = []
    batches = [texts[i:i+batch_size] for i in range(0, len(texts), batch_size)]

    for batch in tqdm(batches, desc="Qwen2.5-3B translating", unit="batch"):
        prompts = [
            tokenizer.apply_chat_template(
                prompt_fn(text),
                tokenize=False,
                add_generation_prompt=True
            )
            for text in batch
        ]

        inputs = tokenizer(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=512
        ).to(model.device)

        outputs = model.generate(
            **inputs,
            max_new_tokens=128,
            do_sample=False,
            temperature=None,
            top_p=None,
            pad_token_id=tokenizer.eos_token_id
        )

        decoded = tokenizer.batch_decode(
            outputs[:, inputs['input_ids'].shape[1]:],
            skip_special_tokens=True
        )
        results.extend([d.strip() for d in decoded])

    return results

sample = test_df.sample(5, random_state=42).reset_index(drop=True)

print("=== Zero-shot sanity check ===")
preds_sample_zs = translate_qwen(
    sample['yorge_cs'].tolist(),
    build_zeroshot_prompt,
    batch_size=4
)

for src, pred, ref in zip(sample['yorge_cs'], preds_sample_zs, sample['english_translation']):
    print(f"CS  : {src}")
    print(f"PRED: {pred}")
    print(f"REF : {ref}")
    print()

print(f"Translating {len(test_sources)} test sentences (zero-shot)...")
preds_qwen_zeroshot = translate_qwen(test_sources, build_zeroshot_prompt, batch_size=4)
print(f"Done!")

print("=" * 65)
print(f"{'Model':<35} {'BLEU':<10} {'chrF++':<10} {'METEOR'}")
print("=" * 65)
bleu_zs, chrf_zs, meteor_zs = evaluate(preds_qwen_zeroshot, test_references, "Qwen2.5-3B Zero-shot")
print("=" * 65)

few_shot_examples = [
    {
        "cs": "Akẹ́kọ̀ọ́ postgraduate ń fẹ́ ṣe Hausaufgabe lórí Computer kí Professor lè fi àmì rere fún wọn.",
        "en": "The postgraduate student wants to do homework on the computer so that the professor can give them good grades."
    },
    {
        "cs": "Àwọn olùwádìí yunifásítì máa lọ sí Vorlesung kutukutu kí wọ́n lè lóye Thema tuntun dáadáa.",
        "en": "The university researchers will go to the lecture early so that they can understand the new topic well."
    },
    {
        "cs": "Ilé iṣẹ́ náà fẹ́ ṣe Expansion sí àwọn ìlú míì.",
        "en": "The company wants to expand into other cities."
    },
    {
        "cs": "Ìsọfúnni nípa Blockwurf ni olùkọ́ fi ránṣẹ́ pẹ̀lú àmì ọwọ́ kí ọmọ ẹgbẹ́ gbọ.",
        "en": "The coach sent information about the block shot through hand signals for team members to understand."
    },
    {
        "cs": "Àwọn Kunden fẹ́ ra Gemüse tuntun ní Markt kí stew lè dùn gan-an lálẹ́.",
        "en": "customers want to buy fresh vegetables at the market so the stew tastes delicious tonight."
    }
]

def build_fewshot_prompt(sentence):
    examples_str = ""
    for i, ex in enumerate(few_shot_examples, 1):
        examples_str += f"Example {i}:\n"
        examples_str += f"CS      : {ex['cs']}\n"
        examples_str += f"English : {ex['en']}\n\n"

    return [
        {
            "role": "system",
            "content": (
                "You are a multilingual translator. "
                "The following sentences are written in Yorùbá-German code-switched form, "
                "where Yorùbá is the matrix language and German is the embedded language. "
                "Translate each sentence to English. "
                "Output only the English translation, nothing else"
                "no explanation, no notes"
            )
        },
        {
            "role": "user",
            "content": (
                f"Here are some examples of Yoruba-German CS sentences and their English translations:\n\n"
                f"{examples_str}"
                f"Now translate this sentence to English:\n"
                f"CS      : {sentence}\n"
                f"English :"
            )
        }
    ]

print("=== Few-shot sanity check ===")
preds_sample_fs = translate_qwen(sample['yorge_cs'].tolist(), build_fewshot_prompt, batch_size=4)

for src, pred, ref in zip(sample['yorge_cs'], preds_sample_fs, sample['english_translation']):
    print(f"CS  : {src}")
    print(f"PRED: {pred}")
    print(f"REF : {ref}")
    print()

print(f"Translating {len(test_sources)} test sentences (few-shot)...")
preds_qwen_fewshot = translate_qwen(test_sources, build_fewshot_prompt, batch_size=4)
print(f"Done!")

print("=" * 65)
print(f"{'Model':<35} {'BLEU':<10} {'chrF++':<10} {'METEOR'}")
print("=" * 65)
evaluate(preds_qwen_zeroshot, test_references, "Qwen2.5-3B Zero-shot")
bleu_fs, chrf_fs, meteor_fs = evaluate(preds_qwen_fewshot, test_references, "Qwen2.5-3B Few-shot")
print("=" * 65)

#Save zero-shot and few-shot results
test_df = test_df.copy()
test_df['prediction_qwen_zs'] = preds_qwen_zeroshot
test_df['prediction_qwen_fs'] = preds_qwen_fewshot
test_df.to_csv("/content/drive/MyDrive/qwen_zs_fs_results_v2.csv", index=False)
print("Saved!")

"""LoRA fine-tuning"""

def format_prompt(row):
    return (
        "<|im_start|>system\n"
        "You are a multilingual translator. "
        "The following sentence is written in Yoruba-German code-switched form, "
        "where Yorùbá is the matrix language and German is the embedded language. "
        "Translate it to English. Output only the English translation, nothing else."
        "<|im_end|>\n"
        "<|im_start|>user\n"
        f"{row['yorge_cs']}"
        "<|im_end|>\n"
        "<|im_start|>assistant\n"
        f"{row['english_translation']}"
        "<|im_end|>"
    )

train_df = train_df.copy()
val_df   = val_df.copy()

train_df['text'] = train_df.apply(format_prompt, axis=1)
val_df['text']   = val_df.apply(format_prompt, axis=1)

print("Sample formatted prompt:")
print(train_df['text'].iloc[0])

class YorGeDataset(TorchDataset):
    def __init__(self, texts, tokenizer, max_length=512):
        self.encodings = tokenizer(
            texts,
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt"
        )
        self.labels = self.encodings['input_ids'].clone()
        # Mask padding positions
        self.labels[self.encodings['attention_mask'] == 0] = -100

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids'     : self.encodings['input_ids'][idx],
            'attention_mask': self.encodings['attention_mask'][idx],
            'labels'        : self.labels[idx]
        }

train_dataset = YorGeDataset(train_df['text'].tolist(), tokenizer)
val_dataset   = YorGeDataset(val_df['text'].tolist(), tokenizer)

sample_check = train_dataset[0]
print(f"Contains -100: {(-100 in sample_check['labels'].unique())}")
print(f"Train dataset : {len(train_dataset)}")
print(f"Val dataset   : {len(val_dataset)}")

#Configure LoRA
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

#Training arguments
training_args = TrainingArguments(
    output_dir="./qwen_lora_yorge_v2",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    warmup_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    logging_steps=20,
    fp16=True,
    report_to="none"
)

# Train
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("Starting Qwen LoRA fine-tuning...")
print(f"Training on {len(train_dataset)} sentences for 5 epochs...")
trainer.train()
print("Fine-tuning complete!")

#Save LoRA adapters
save_path = "/content/drive/MyDrive/qwen_lora_yorge_v2"
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print(f"Saved to: {save_path}")

# Load fine-tuned model for evaluation
print("Loading base Qwen2.5-3B model...")
base_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-3B-Instruct",
    device_map="auto",
    torch_dtype=torch.float16
)

print("Merging LoRA adapters...")
ft_model = PeftModel.from_pretrained(base_model, "/content/drive/MyDrive/qwen_lora_yorge_v2")
ft_model = ft_model.merge_and_unload()
print("Fine-tuned Qwen2.5-3B model ready!")

# Translation function
def translate_finetuned(texts, batch_size=4):
    results = []
    batches = [texts[i:i+batch_size] for i in range(0, len(texts), batch_size)]

    for batch in tqdm(batches, desc="Qwen2.5-3B LoRA translating", unit="batch"):
        prompts = [
            tokenizer.apply_chat_template(
                [
                    {
                        "role": "system",
                        "content": (
                            "You are a multilingual translator. "
                            "The following sentence is written in Yoruba-German "
                            "code-switched form, where Yorùbá is the matrix language "
                            "and German is the embedded language. Translate it to "
                            "English. Output only the English translation, nothing else."
                        )
                    },
                    {"role": "user", "content": text}
                ],
                tokenize=False,
                add_generation_prompt=True
            )
            for text in batch
        ]

        inputs = tokenizer(
            prompts, return_tensors="pt", padding=True,
            truncation=True, max_length=512
        ).to(ft_model.device)

        outputs = ft_model.generate(
            **inputs, max_new_tokens=128, do_sample=False,
            temperature=None, top_p=None,
            pad_token_id=tokenizer.eos_token_id
        )

        decoded = tokenizer.batch_decode(
            outputs[:, inputs['input_ids'].shape[1]:],
            skip_special_tokens=True
        )
        results.extend([d.strip() for d in decoded])

    return results

# Translate test set
print(f"Translating {len(test_sources)} test sentences...")
preds_qwen_lora = translate_finetuned(test_sources, batch_size=4)
print("Done!")

# ── Evaluate (BLEU, chrF++, METEOR)
bleu_lora, chrf_lora, meteor_lora = evaluate(preds_qwen_lora, test_references, "Qwen2.5-3B + LoRA")

#Save results
test_df['prediction_qwen_lora'] = preds_qwen_lora
test_df.to_csv("/content/drive/MyDrive/qwen_all_results_v2.csv", index=False)
print("Saved to qwen_all_results_v2.csv!")

import subprocess
subprocess.run(['pip', 'install', 'bert-score', '-q'])

# import BERTScore first
from bert_score import score as bert_score
print("BERTScore imported successfully!")

# load saved results
import pandas as pd

test_df = pd.read_csv("/content/drive/MyDrive/qwen_all_results_v2.csv")

test_references = test_df['english_translation'].tolist()
preds_zs = test_df['prediction_qwen_zs'].tolist()
preds_fs = test_df['prediction_qwen_fs'].tolist()
preds_lora = test_df['prediction_qwen_lora'].tolist()

print(f"Loaded {len(test_df)} rows")

# Compute BERTScore for all three settings
print("Computing BERTScore for zero-shot...")
P_zs, R_zs, F1_zs = bert_score(preds_zs, test_references, lang="en", verbose=True)

print("\nComputing BERTScore for few-shot...")
P_fs, R_fs, F1_fs = bert_score(preds_fs, test_references, lang="en", verbose=True)

print("\nComputing BERTScore for LoRA...")
P_lora, R_lora, F1_lora = bert_score(preds_lora, test_references, lang="en", verbose=True)

#Results
print("=" * 55)
print(f"{'Model':<30} {'BERTScore F1'}")
print("=" * 55)
print(f"{'Qwen2.5-3B Zero-shot':<30} {F1_zs.mean().item():.4f}")
print(f"{'Qwen2.5-3B Few-shot':<30} {F1_fs.mean().item():.4f}")
print(f"{'Qwen2.5-3B + LoRA':<30} {F1_lora.mean().item():.4f}")
print("=" * 55)