# -*- coding: utf-8 -*-
"""YorGe CS NLLB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M17CZxTWqgHMWBk4gDF_axpaglGHqBrS
"""

!pip install transformers peft sentencepiece sacrebleu nltk tqdm -q

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset as TorchDataset
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
from sacrebleu.metrics import BLEU, CHRF
from nltk.translate.meteor_score import meteor_score
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

print("All imports successful!")

#Load dataset
df = pd.read_csv("/content/drive/MyDrive/yorge_cs.csv")

print(f"Total rows : {len(df)}")
print(df['domain'].value_counts())
df.head(3)

train_df, temp_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['domain']
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, random_state=42, stratify=temp_df['domain']
)

print(f"Train : {len(train_df)} sentences")
print(f"Val   : {len(val_df)} sentences")
print(f"Test  : {len(test_df)} sentences")

test_sources    = test_df['yorge_cs'].tolist()
test_references = test_df['english_translation'].tolist()

model_name = "facebook/nllb-200-3.3B"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Loading model...")
model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)
print("NLLB-200-3.3B loaded!")

bleu_metric = BLEU(effective_order=True)
chrf_metric = CHRF()

def evaluate(preds, refs, label):
    b = bleu_metric.corpus_score(preds, [refs])
    c = chrf_metric.corpus_score(preds, [refs])
    m = np.mean([
        meteor_score([ref.split()], pred.split())
        for ref, pred in zip(refs, preds)
    ])
    print(f"{label:<35} {b.score:<10.2f} {c.score:<10.2f} {m:.4f}")
    return b.score, c.score, m

def translate_nllb(texts, src_lang="yor_Latn", tgt_lang="eng_Latn", batch_size=8):
    tokenizer.src_lang = src_lang
    forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)
    results = []
    batches = [texts[i:i+batch_size] for i in range(0, len(texts), batch_size)]

    for batch in tqdm(batches, desc=f"NLLB {src_lang}\u2192{tgt_lang}", unit="batch"):
        inputs = tokenizer(
            batch, return_tensors="pt", padding=True,
            truncation=True, max_length=256
        ).to(model.device)

        outputs = model.generate(
            **inputs,
            forced_bos_token_id=forced_bos_token_id,
            max_new_tokens=256
        )
        decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        results.extend(decoded)

    return results

sample = test_df.sample(5, random_state=42).reset_index(drop=True)

preds_sample = translate_nllb(sample['yorge_cs'].tolist(), batch_size=4)

for src, pred, ref in zip(sample['yorge_cs'], preds_sample, sample['english_translation']):
    print(f"CS  : {src}")
    print(f"PRED: {pred}")
    print(f"REF : {ref}")
    print()

print(f"Translating {len(test_sources)} test sentences (zero-shot)...")
preds_nllb_zeroshot = translate_nllb(test_sources, batch_size=8)
print("Done!")

print("=" * 65)
print(f"{'Model':<35} {'BLEU':<10} {'chrF++':<10} {'METEOR'}")
print("=" * 65)
bleu_zs, chrf_zs, meteor_zs = evaluate(preds_nllb_zeroshot, test_references, "NLLB-200-3.3B Zero-shot")
print("=" * 65)
print(f"Evaluated on {len(test_references)} test sentences")

test_df = test_df.copy()
test_df['prediction_nllb_zs'] = preds_nllb_zeroshot
test_df.to_csv("/content/drive/MyDrive/nllb_zeroshot_test_results.csv", index=False)
print("Saved!")

"""LoRA fine-tuning"""

class YorGeSeq2SeqDataset(TorchDataset):
    def __init__(self, sources, targets, tokenizer, src_lang="yor_Latn",
                 tgt_lang="eng_Latn", max_length=256):
        tokenizer.src_lang = src_lang
        self.inputs = tokenizer(
            sources, truncation=True, padding="max_length",
            max_length=max_length, return_tensors="pt"
        )

        labels = tokenizer(
            targets, truncation=True, padding="max_length",
            max_length=max_length, return_tensors="pt"
        )


        label_ids = labels['input_ids'].clone()
        label_ids[label_ids == tokenizer.pad_token_id] = -100
        self.labels = label_ids

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids'     : self.inputs['input_ids'][idx],
            'attention_mask': self.inputs['attention_mask'][idx],
            'labels'        : self.labels[idx]
        }

train_sources = train_df['yorge_cs'].tolist()
train_targets = train_df['english_translation'].tolist()
val_sources   = val_df['yorge_cs'].tolist()
val_targets   = val_df['english_translation'].tolist()

train_dataset = YorGeSeq2SeqDataset(train_sources, train_targets, tokenizer)
val_dataset   = YorGeSeq2SeqDataset(val_sources, val_targets, tokenizer)


sample_check = train_dataset[0]
print(f"Contains -100: {(-100 in sample_check['labels'].unique())}")
print(f"Train dataset : {len(train_dataset)}")
print(f"Val dataset   : {len(val_dataset)}")

!pip install --upgrade torchao

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "out_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

training_args = Seq2SeqTrainingArguments(
    output_dir="./nllb_lora_yorge",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    warmup_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    logging_steps=20,
    fp16=True,
    predict_with_generate=False,
    report_to="none"
)

#Train
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("Starting NLLB LoRA fine-tuning...")
print(f"Training on {len(train_dataset)} sentences for 5 epochs...")
trainer.train()
print("Fine-tuning complete!")

save_path = "/content/drive/MyDrive/nllb_lora_yorge"
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print(f"Saved to: {save_path}")

print("Loading base NLLB model...")
base_model = AutoModelForSeq2SeqLM.from_pretrained(
    "facebook/nllb-200-3.3B",
    device_map="auto",
    torch_dtype=torch.float16
)

print("Merging LoRA adapters...")
ft_model = PeftModel.from_pretrained(base_model, save_path)
ft_model = ft_model.merge_and_unload()
print("Fine-tuned NLLB model ready!")

def translate_nllb_finetuned(texts, src_lang="yor_Latn", tgt_lang="eng_Latn", batch_size=8):
    tokenizer.src_lang = src_lang
    forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)
    results = []
    batches = [texts[i:i+batch_size] for i in range(0, len(texts), batch_size)]

    for batch in tqdm(batches, desc="NLLB LoRA translating", unit="batch"):
        inputs = tokenizer(
            batch, return_tensors="pt", padding=True,
            truncation=True, max_length=256
        ).to(ft_model.device)

        outputs = ft_model.generate(
            **inputs,
            forced_bos_token_id=forced_bos_token_id,
            max_new_tokens=256
        )
        decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        results.extend(decoded)

    return results

preds_sample_lora = translate_nllb_finetuned(sample['yorge_cs'].tolist(), batch_size=4)

for src, pred, ref in zip(sample['yorge_cs'], preds_sample_lora, sample['english_translation']):
    print(f"CS  : {src}")
    print(f"PRED: {pred}")
    print(f"REF : {ref}")
    print()

print(f"Translating {len(test_sources)} test sentences (LoRA)...")
preds_nllb_lora = translate_nllb_finetuned(test_sources, batch_size=8)
print("Done!")

print("=" * 65)
print(f"{'Model':<35} {'BLEU':<10} {'chrF++':<10} {'METEOR'}")
print("=" * 65)
evaluate(preds_nllb_zeroshot, test_references, "NLLB-200-3.3B Zero-shot")
evaluate(preds_nllb_lora,     test_references, "NLLB-200-3.3B + LoRA")
print("=" * 65)

test_df['prediction_nllb_lora'] = preds_nllb_lora
test_df.to_csv("/content/drive/MyDrive/nllb_all_results.csv", index=False)
print("Saved!")

"""###BERTScore Metric Evaluation

BERTScore F1 is computed alongside BLEU, chrF++, and METEOR to capture semantic similarity via contextual embeddings rather than exact n-gram overlap. Scores are computed directly from saved zero-shot and LoRA prediction CSVs, requiring no retranslation.
"""

!pip install bert-score -q
import bert_score

# import BERTScore first
from bert_score import score as bert_score
print("BERTScore imported successfully!")

# Reload  saved NLLB results
import pandas as pd

test_df = pd.read_csv("/content/drive/MyDrive/nllb_all_results.csv")

references = test_df['english_translation'].tolist()
preds_zs = test_df['prediction_nllb_zs'].tolist()
preds_lora = test_df['prediction_nllb_lora'].tolist()

#Compute BERTScore for zero-shot and LoRA
print("Computing BERTScore for zero-shot...")
P_zs, R_zs, F1_zs = bert_score(preds_zs, references, lang="en", verbose=True)

print("\nComputing BERTScore for LoRA...")
P_lora, R_lora, F1_lora = bert_score(preds_lora, references, lang="en", verbose=True)

#Results
print("=" * 55)
print(f"{'Model':<30} {'BERTScore F1'}")
print("=" * 55)
print(f"{'NLLB-200-3.3B Zero-shot':<30} {F1_zs.mean().item():.4f}")
print(f"{'NLLB-200-3.3B + LoRA':<30} {F1_lora.mean().item():.4f}")
print("=" * 55)